project:
  type: website
  output-dir: docs

website:
  title: "Haoqi Wang"
  navbar:
    right:
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


